DEVOPS-386 : Reusable workflow & actions to build & deploy assets
Sonergia/github-reusable-workflows pull request #16
Opened 2023-10-31 09:29 UTC by Kloranis

Les références à la branche en PR `ref=tech/DEVOPS-386` sont à remplacer par `2.x` avant de faire le merge

2023-10-31 15:00 UTC, jledoux-sonergia requested changes

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +        echo "" >> $GITHUB_STEP_SUMMARY
Est ce qu'il ne faudrait pas provoquer un "exit 1" si le fichier env n'est pas trouvé ? Car la CICD ne peut pas continuer dans ce cas et plantera probablement avant la fin mais en ayant traité des steps inutiles, ou bien considères tu cette étape comme optionnelle ?

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +      uses: Sonergia/github-reusable-workflows/.github/actions/npm-build@tech/DEVOPS-386
Attention à ne pas oublier de changer la ref git au moment du merge

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +      uses: Sonergia/github-reusable-workflows/.github/actions/pnpm-build@tech/DEVOPS-386
Attention à ne pas oublier de changer la ref git au moment du merge

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +      uses: Sonergia/github-reusable-workflows/.github/actions/yarn-build@tech/DEVOPS-386
Attention à ne pas oublier de changer la ref git au moment du merge

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/deploy-assets.yml
> +        uses: sonergia/github-reusable-workflows/.github/actions/build-node-app@tech/DEVOPS-386
Attention à ne pas oublier de changer la ref git au moment du merge

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/deploy-assets.yml
> +        uses: sonergia/github-reusable-workflows/.github/actions/deploy-cdn@tech/DEVOPS-386
Attention à ne pas oublier de changer la ref git au moment du merge

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +
Les quotes sont inutiles ici il me semble

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/npm-build/action.yml
> +    required: true
pas de valeur par défaut ici ? A mon sens c'est au niveau le plus bas qu'elles ont le plus d'intérêt puisque cela évite les répétitions multiples dans les niveaux supérieurs

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/pnpm-build/action.yml
> +    required: true
Même remarque ici, pourquoi pas de valeur par défaut ?

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/yarn-build/action.yml
> +    required: true
Même remarque ici, pourquoi pas de valeur par défaut ?

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/yarn-build/action.yml
> +      run: yarn run build
Est ce que cela fonctionne en mode "--non-interactive" ?

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/npm-build/action.yml
> +      run: npm install
Si la var d'env NODE_ENV n'est pas définie à "production", je crois qu'il faut ajouter le paramètre "--omit=dev" pour ne pas embarquer les dev dependancies.
https://docs.npmjs.com/cli/v8/commands/npm-install#omit

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/pnpm-build/action.yml
> +      run: pnpm install --frozen-lockfile
Même remarque ici, si la var d'env NODE_ENV n'est pas définie à "production", je crois qu'il faut ajouter le paramètre "--prod" pour ne pas embarquer les dev dependancies.
https://pnpm.io/cli/install#--prod--p

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/scripts/set-context.sh
>      # New ECS infra expects CLUSTER var instead of ENVIRONMENT => to fix
Rajouter la notation "# TODO" à ce commentaire au passage, la var CLUSTER doit disparaître au profit de ENVIRONMENT

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +        echo "- Dossier du build dans l'archive : ${{ inputs.BUILD_DIRECTORY }}" >> $GITHUB_STEP_SUMMARY
Peut être qu'il faudrait imaginer et conditionner plusieurs summary selon si l'action a fonctionnée ou non, car au final le plus utile c'est de savoir pourquoi ça a planté et de donner un max d'indications pour éviter que ça ne remonte aux DevOps si l'erreur vient du développeur et qu'il peut la corriger seul

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/check-context.yml
Pourquoi remplacer les simple quotes par des doubles ? GitHub préconise plutôt l'usage des simples quotes https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
Ce n'est pas explicite dans la documentation, mais tous les exemples utilisent des simples quotes.

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/check-context.yml
> +          ref: "tech/DEVOPS-386"
Attention à ne pas oublier de changer la ref git au moment du merge et ne pas changer les quotes

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/check-context.yml
> +        run: |
En cas d'erreur sur une des steps précédentes le summary ne s'affichera pas sans une condition du type `if: always()`

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/deploy-assets.yml
> +      - id: build-assets
De manière générale, il vaut mieux éviter de réutiliser les libellés des jobs dans les steps pour éviter les confusions quand on y fait référence ailleurs. 
Ici l'idéal serait plutôt d'utiliser le nom de l'action `build-node-app` comme ID, mais c'est discutable, si ça te paraît plus clair, laisse en l'état.

2023-10-31 15:00 UTC, jledoux-sonergia commented on .github/workflows/deploy-assets.yml
> +        run: aws cloudfront create-invalidation --distribution-id ${{ needs.deploy-cdn.outputs.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
Une idée pour le TODO pourrait être de se baser sur la "conlusion" du job `build-assets` si celui-ci a été "skipped", cela peut indiquer qu'il s'agit d'un "re-run" (par ex) et qu'on peut donc également skipper ces deux steps

2023-11-03 14:40 UTC, Kloranis commented on .github/actions/yarn-build/action.yml
> +      run: yarn run build
Bonne quesion, la responsabilité se trouve dans la déclaration du script dans le package.json

2023-11-03 14:45 UTC, Kloranis commented on .github/actions/npm-build/action.yml
> +      run: npm install
Les packages de développement sont nécessaires, les scripts "react-scripts" en font partie et sont nécessaires au build

2023-11-03 14:46 UTC, Kloranis commented on .github/actions/pnpm-build/action.yml
> +      run: pnpm install --frozen-lockfile
Même réponse :smile:

2023-11-03 15:31 UTC, jledoux-sonergia requested changes

2023-11-03 15:31 UTC, jledoux-sonergia commented on .github/actions/npm-build/action.yml
> +      run: npm install
Est ce que c'est dû à un défaut de conception ? Les dev dépendancies ne doivent pas être incluses, ça alourdit le process de build, l'artefact et cela peut également introduire des failles de sécurité vu qu'ils ne sont pas pensé pour la production

2023-11-03 15:31 UTC, jledoux-sonergia commented on .github/actions/yarn-build/action.yml
> +      run: yarn run build
A voir à l'usage, le build n'est pas censé être intéractif de teoute façon, mais le process d'install peut l'être

2023-11-03 15:31 UTC, jledoux-sonergia commented on .github/actions/build-node-app/action.yml
> +        fi
Je me demande si se baser sur la conclusion = success de l'upload n'est pas trop restrictif pour identifier le succès de la step.
A voir si la conclusion de l'upload peut être "skipped" en cas de re-run, ou bien si une archive identique est déjà en cache (s'il y en a) et que dans ce cas elle se retrouve "skipped"

2023-12-01 09:39 UTC, jledoux-sonergia approved these changes

2023-12-01 09:40 UTC, merged